### ISSUE TITLE
Question Marks only

### ISSUE THREAD

**Issue by gacrichards** [mattmaddux/FASwiftUI#1]
Followed the integration steps in the readme and everything went well, however when I try to use the icons I only get the question mark in a box. I've tried "bluetooth-b", "signal", and "bomb" used in your example. I've also tried to prefix these with the "fa-" with no luck.

**Comment by mattmaddux** [comment]
Double check that the files you dropped into the project are included in the target. For each .otf file and icons.json do the following:
- Select the file in the Project Navigator
- Open the Inspectors bar on the right and select the file inspector (first tab)
- Under Target Membership select each target you want it included in

Let me know if it works and I'll add it to the install instructions.

**Comment by mattmaddux** [comment]
Oh, and you don't need to use the "fa-" prefix. Though now that I think of it, I should make it work either way.

**Comment by gacrichards** [comment]
That was it, thanks!
:man_facepalming: I feel like I should've known better but hopefully adding a reminder in the instructions will help the more ignorant of us.

**Comment by mattmaddux** [comment]
Well it's definitely a common issue, I'll update the instructions.
