### ISSUE TITLE
icons not displaying. getting a squared question mark

### ISSUE THREAD

**Issue by pprevalon** [mattmaddux/FASwiftUI#10]
I'm getting a square with a question mark I'm not sure why this happens.

my code.
            FAText(iconName: "bomb", size: 21)

**Comment by PedroCavaleiro** [comment]
Same happening to me, made sure that all font files and json file were being targeted by my projects, and added the "Fonts provided by application" key into the Info.plist

Any idea why it's happening?

**Comment by mattmaddux** [comment]
Hey guys, sorry for the delay, I haven't been tending this repo much. Double check that the files are added to the target (step 4 in the instructions in the readme). For some reason Xcode doesn't like adding those fonts automatically.

**Comment by mattmaddux** [comment]
Closing issue now, reopen if issue persists.
