### ISSUE TITLE
Some icons shows as question mark

### ISSUE THREAD

**Issue by Zalarudo** [mattmaddux/FASwiftUI#13]
Some icons are shown as question marks. 
What I did: 
1) Installed the package.
<img width="802" alt="Снимок экрана 2022-05-04 в 17 46 17" src="https://user-images.githubusercontent.com/52541279/166706794-0e74ec16-27ec-40ea-b470-b553be1b12d6.png">

2) Connected all the files in the inspector 
<img width="1660" alt="Снимок экрана 2022-05-04 в 17 46 39" src="https://user-images.githubusercontent.com/52541279/166706886-ac178289-0988-4e43-ba7c-5335fb797fa5.png">

3) put all data into info plist
<img width="981" alt="Снимок экрана 2022-05-04 в 17 47 01" src="https://user-images.githubusercontent.com/52541279/166706984-f9ce29cb-eff2-4d47-a97b-ab50bf577548.png">

As Result some icons are Questions& In this example its "running" icon
<img width="445" alt="Снимок экрана 2022-05-04 в 17 48 13" src="https://user-images.githubusercontent.com/52541279/166707238-fb3b7e96-b73a-4ce8-a96a-f2574e3bd989.png">

Version FA - 5.15.4 For The Desktop
Version xCode - 13.2.1

**Comment by mattmaddux** [comment]
Would you mind posting your code?
