### ISSUE TITLE
Add fallback and error logging for missing styles and incorrect names

### ISSUE THREAD

**Issue by alexis-ag** [mattmaddux/FASwiftUI#4]
i've
* added package dependancy
* copied icons.json and three font files *.otf to my project
* added them to the target
* added to info.plist new section "Fonts provided by application" with three items (like 'Font Awesome 5 Brands-Regular-400.otf' without quotation)
* i've added "FAText(iconName: "bomb", size: 50)" to the view
* and all what i see is a question icon
<img width="1543" alt="Screenshot 2020-02-17 at 18 14 14" src="https://user-images.githubusercontent.com/11797926/74666001-c8507a00-51b1-11ea-83e7-696bdc0bd400.png">

what am i doing wrong? could you help me?

**Comment by mattmaddux** [comment]
Sure, would you mind posting the source code for the view you’re trying?

**Comment by alexis-ag** [comment]
yeah, also i attached a source code with simple oneview swiftui proj

import SwiftUI
import FASwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Text("Hello, World!")
            FAText(iconName: "bomb", size: 200)
        }
    }
}
[font_awesome.zip](https://github.com/mattmaddux/FASwiftUI/files/4215812/font_awesome.zip)

**Comment by mattmaddux** [comment]
Great. Will try to figure it out tonight.

**Comment by mattmaddux** [comment]
So you haven't actually checked the Target Membership box for each of the font files. Try that for each of them and try again.

![Screen Shot 2020-02-17 at 8 46 16 PM](https://user-images.githubusercontent.com/6632566/74699755-23d93280-51c7-11ea-9fb0-4d818c40995a.png)

**Comment by alexis-ag** [comment]
it's strange because i put it in target while adding files to the project
so, i've added them
 and a result is the same 
[font_awesome.zip](https://github.com/mattmaddux/FASwiftUI/files/4217877/font_awesome.zip)

thanks for paying attention

**Comment by mattmaddux** [comment]
Yeah, it's a little odd that for the .otf files you always have to manually add the target. Not sure why.

But I figured out what was going on, the regular style of "bomb" is not included in the free FA set, only solid. So if you try this view...

```
import SwiftUI
import FASwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Text("Hello, World!")
            FAText(iconName: "bomb", size: 200, style: .solid)
            FAText(iconName: "flag", size: 200)
        }
    }
}

struct Test_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

...you'll notice they both work with your project (both regular and solid are included in the free set for "flag").

I should try to figure out some fallback to available types, or error messaging. But to see all the available versions I'd have to include a list, which I don't want to maintain.

I'll think about how this can be handled better.

(And maybe I should change my examples in the readme to something that's in the free FA set.)

**Comment by alexis-ag** [comment]
cool, thanks for helping me

**Comment by mattmaddux** [comment]
Done with 1.0.4 release.
