### ISSUE TITLE
on free plan lib fails when i try to show unsupported icon 

### ISSUE THREAD

**Issue by alexis-ag** [mattmaddux/FASwiftUI#5]
for example: 
FAText(iconName: "bomb2", size: 50)
i think you forgot to add "question-square" icon to free the lib

<img width="1468" alt="Screenshot 2020-02-20 at 13 39 38" src="https://user-images.githubusercontent.com/11797926/74926367-d5a27a00-53e6-11ea-97be-15b239795f1b.png">

**Comment by mattmaddux** [comment]
This is now fixed in the new 1.0.4 release. From the notes:

> Missing icons will now fall back to “question-circle” available in the FA free set, and an error message will be printed.
> 
> If no style is specified and “regular” is not available, the first available style will be used instead, but silently.
> 
> If a style is specified but unavailable, same behavior as above, but an error message will be printed to log.
