### ISSUE TITLE
Fatal error in Initializer

### ISSUE THREAD

**Issue by georglang** [mattmaddux/FASwiftUI#8]
Hi Matt,

when using your Package i get the error: Fatal error: Unexpectedly found nil while unwrapping an Optional value
it appears in  class FontAwesome line 30.
let fileURL = Bundle.main.url(forResource: "icons", withExtension: "json")!

**Comment by mattmaddux** [comment]
Double check the installation instructions in the readme and make sure you've imported icons.json and all the appropriate font files.

Comment again here if that's not it.

**Comment by mattmaddux** [comment]
I really shouldn't be force unwrapping that. I think it was temporary and I forgot to change it. Should fail more gracefully.

**Comment by mattmaddux** [comment]
Will close issue now, reopen if issue persists.
