### ISSUE TITLE
Some FAText icons are question marks.

### ISSUE THREAD

**Issue by supremevance** [mattmaddux/FASwiftUI#9]
All of my FATexts are question marks. I tried using the icon by the name of "save" and it worked but no other icons will show.

**Comment by mattmaddux** [comment]
Could you do a few things for me?

1. Double check each step of the installation instructions and make sure they're done (especially step 4)
2. Post some sample code
3. Let me know what version of Xcode and iOS/MacOS you're using

Thanks!

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.

**Comment by supremevance** [comment]
I ended up figuring it out, I was missing the .otf extension in the info.plist. I had it for the one of the fonts and that is why the save icon worked.
